export const initialPreformState = {
  firstName: "",
  lastName: "",
  cnp: "",
  birthDate: "",
  sex: "",
  age: "",
  phoneNumber: "",
  email: "",

  sheetNumber: "",
  presentationDate: "",
  presentationTime: "",
  takenOverBy: "",

  county: "",
  locality: "",
  street: "",
  streetNumber: "",
  building: "",
  staircase: "",
  floor: "",
  apartment: "",

  patientStateCode: "",

  gcsHour: "",
  gcsM: "",
  gcsV: "",
  gcsO: "",
  gcs: "",

  broughtByCode: "",
  broughtByOther: "",

  broughtFromCode: "",
  broughtFromOther: "",

  pickupDeceased: false,
  pickupStopCr: false,
  pickupResuscitationInProgress: false,
  pickupTrauma: false,
  resuscitationHour: "",
  resuscitationSuccessful: false,
  resuscitationFailed: false,
  deathHour: "",
  resuscitationNotStartedReason: "",

  triageColor: "",
  arrivalMode: "MIJLOACE_PROPRII",
  reason: "",

  respiratoryRate: "",
  pulse: "",
  systolicBp: "",
  diastolicBp: "",
  spo2: "",
  temperature: "",
  glycemia: "",
  trc: "",

  historyCardiac: false,
  historyNeurologic: false,
  historyRenal: false,
  historyPulmonary: false,
  historyTbc: false,
  historyHepatic: false,
  historyGastric: false,
  historyDiabetes: false,
  historyInfectious: false,
  historyStd: false,
  historyOther: "",

  anamnesis: "",

  heightCm: "",
  weightKg: "",

  triageFever: false,
  triageAsthenia: false,
  triageDizziness: false,

  objectiveGeneralState: "",

  headNormal: false,
  headTraumaMark: false,
  headOralLesions: false,
  headDentalLesions: false,

  neckNormal: false,
  neckTraumaMark: false,
  neckPalpableFormations: false,
  neckOther: "",

  noseNormal: false,
  noseNostrilsNormal: false,
  noseMucosaNormal: false,
  noseOther: "",
  noseEpistaxisLeft: false,
  noseEpistaxisRight: false,
  noseForeignBodyLeft: false,
  noseForeignBodyRight: false,
  noseTraumaLeft: false,
  noseTraumaRight: false,

  earNormal: false,
  earTympanicMembraneNormal: false,
  earExternalCanalsNormal: false,
  earAuricleNormal: false,
  earOther: "",
  earOtorrhagiaLeft: false,
  earOtorrhagiaRight: false,
  earForeignBodyLeft: false,
  earForeignBodyRight: false,
  earHemotympanumLeft: false,
  earHemotympanumRight: false,
  earTraumaLeft: false,
  earTraumaRight: false,

  eyeNormal: false,
  eyeMobilityNormal: false,
  eyePupilsNormal: false,
  eyeExamOther: "",
  eyeConjunctivitisLeft: false,
  eyeConjunctivitisRight: false,
  eyeMydriasisLeft: false,
  eyeMydriasisRight: false,
  eyeMiosisLeft: false,
  eyeMiosisRight: false,
  eyeNystagmusLeft: false,
  eyeNystagmusRight: false,
  eyeDeviationLeft: false,
  eyeDeviationRight: false,
  eyeTraumaExamLeft: false,
  eyeTraumaExamRight: false,

  cvRhythmNormal: false,
  cvPeripheralPulseNormal: false,
  cvHeartAuscultationNormal: false,
  cvIrregularPulse: false,
  cvFiliformPeripheralPulse: false,
  cvPulseDeficit: false,
  cvArrhythmicSounds: false,
  cvMuffledSounds: false,
  cvPericardialRub: false,
  cvJugularTurgor: false,
  cvSystolicMurmur: false,
  cvDiastolicMurmur: false,
  cvAorticMurmur: false,
  cvGallop: false,
  cvCarotidMurmur: false,
  cvObservations: "",

  respNormal: false,
  respThoraxAspectNormal: false,
  respThoraxPercussionNormal: false,
  respVesicularBilateralNormal: false,
  respOropharynxNormal: false,
  respDiminishedMurmurLeft: false,
  respDiminishedMurmurRight: false,
  respAbsentMurmurLeft: false,
  respAbsentMurmurRight: false,
  respWheezingRalesLeft: false,
  respWheezingRalesRight: false,
  respCrepitantRalesLeft: false,
  respCrepitantRalesRight: false,
  respSubcrepitantRalesLeft: false,
  respSubcrepitantRalesRight: false,
  respIntercostalRetractionLeft: false,
  respIntercostalRetractionRight: false,
  respSubcutaneousEmphysemaLeft: false,
  respSubcutaneousEmphysemaRight: false,
  respTracheaDeviationLeft: false,
  respTracheaDeviationRight: false,
  respWheezing: false,
  respOther: "",

  eyeAcuteVisionLoss: false,
  eyeVisionDisorders: false,
  eyeForeignBody: false,
  eyeOtherManifestations: false,

  burnAirwayAffected: false,
  burnFlame: false,
  burnSolid: false,
  burnLiquid: false,
  burnVaporsGas: false,
  burnChemical: false,

  chestPain: false,
  dyspnea: false,
  hemoptysis: false,
  cough: false,
  expectoration: false,

  psychDepression: false,
  psychBehaviorDisorder: false,
  psychSuicide: false,
  psychHallucinations: false,
  psychDelirium: false,

  giNausea: false,
  giVomiting: false,
  giTransitDisorders: false,
  giRectorrhagia: false,
  giMelena: false,
  giHematemesis: false,
  giAbdominalPain: false,

  neuroConvulsions: false,
  neuroMyoclonus: false,
  neuroHeadache: false,
  neuroParalysis: false,

  guUrinationDisorders: false,
  guDysuria: false,
  guPollakiuria: false,
  guOliguria: false,
  guHematuria: false,
  guVaginalBleeding: false,
  guPregnancy: false,

  skinWarm: false,
  skinCold: false,
  skinWet: false,
  skinPale: false,
  skinCyanotic: false,
  skinJaundice: false,
  skinEcchymosis: false,
  skinRash: false,
  skinPruritus: false,
  skinBurns: false,

  locomotorInflammation: false,
  locomotorSwelling: false,
  locomotorPain: false,
  locomotorFunctionalImpairment: false,
  locomotorHematoma: false,

  abdomenNormal: false,
  abdomenPalpation: false,
  abdomenPercussion: false,
  abdomenBowelTransit: false,
  abdomenRectalExam: false,
  abdomenDistended: false,
  abdomenTransitAbsent: false,
  abdomenHepatomegaly: false,
  abdomenSplenomegaly: false,
  abdomenPalpableMass: false,
  abdomenTenderness: false,
  abdomenRectalPositive: false,
  abdomenPeritonealIrritation: false,
  abdomenObservations: "",

  skinExamNormal: false,
  skinExamWarm: false,
  skinExamCold: false,
  skinExamWet: false,
  skinExamDry: false,
  skinExamPruritus: false,
  skinExamExcoriations: false,
  skinExamEcchymosis: false,
  skinExamPetechiae: false,
  skinExamPurpura: false,
  skinExamJaundice: false,
  skinExamWounds: false,
  skinExamPale: false,
  skinExamCyanosis: false,
  skinExamSweaty: false,
  skinExamOther: "",
  skinExamLocation: "",

  guExamNormal: false,
  guExternalGenitals: false,
  guRegularMenstruation: false,
  guRectalExam: false,
  guLastMenstruationDate: "",
  guBloodyVaginalDischarge: false,
  guLeucorrhea: false,
  guCervixSensitivity: false,
  guEnlargedUterus: false,
  guLateroUterineMass: false,
  guGiordanoLeft: false,
  guGiordanoRight: false,
  guTesticularSwellingLeft: false,
  guTesticularSwellingRight: false,
  guTesticularPainLeft: false,
  guTesticularPainRight: false,
  guBreastMassLeft: false,
  guBreastMassRight: false,
  guTraumaLeft: false,
  guTraumaRight: false,
  guExamHematuria: false,
  guExamOther: "",

  locomotorExamNormal: false,
  locomotorHead: false,
  locomotorNeck: false,
  locomotorTrunk: false,
  locomotorUpperLimbs: false,
  locomotorLowerLimbs: false,

  locomotorPulseCarotidLeft: false,
  locomotorPulseCarotidRight: false,
  locomotorPulseBrachialLeft: false,
  locomotorPulseBrachialRight: false,
  locomotorPulseRadialLeft: false,
  locomotorPulseRadialRight: false,
  locomotorPulseFemoralLeft: false,
  locomotorPulseFemoralRight: false,
  locomotorPulsePoplitealLeft: false,
  locomotorPulsePoplitealRight: false,
  locomotorPulsePedialLeft: false,
  locomotorPulsePedialRight: false,

  locomotorExamPain: false,
  locomotorExamSwelling: false,
  locomotorExamEdema: false,
  locomotorExamFunctionalImpairment: false,
  locomotorExamCyanosis: false,
  locomotorExamOpenFracture: false,
  locomotorExamClosedFracture: false,
  locomotorExamObservations: "",

  neuroPsychNormal: false,
  neuroPsychOriented: false,
  neuroPsychCranialNerves: false,
  neuroPsychMotor: false,
  neuroPsychSensitive: false,
  neuroPsychRot: false,
  neuroPsychHallucinations: false,
  neuroPsychDelirium: false,
  neuroPsychBehaviorDisorders: false,
  neuroPsychAgitated: false,
  neuroPsychObnubilated: false,
  neuroPsychConfused: false,
  neuroPsychPhotophobia: false,
  neuroPsychNeckStiffness: false,
  neuroPsychParesthesia: false,
  neuroPsychAtaxia: false,
  neuroPsychAphasia: false,
  neuroPsychMyoclonus: false,
  neuroPsychConvulsions: false,

  neuroPsychPlegiaLeft: false,
  neuroPsychPlegiaRight: false,
  neuroPsychParesisLeft: false,
  neuroPsychParesisRight: false,
  neuroPsychAnesthesiaLeft: false,
  neuroPsychAnesthesiaRight: false,
  neuroPsychBabinskiLeft: false,
  neuroPsychBabinskiRight: false,
  neuroPsychOther: "",
  neuroPsychObservations: "",

  proceduresO2Mask: false,
  proceduresO2MaskValue: "",

  proceduresGuedelCannula: false,
  proceduresOralCavityAspiration: false,
  proceduresIotTubeAspiration: false,
  proceduresIotTubeAspirationValue: "",

  proceduresIotWithInduction: false,
  proceduresIotWithoutInduction: false,
  proceduresIntWithInduction: false,
  proceduresCombitube: false,
  proceduresLaryngealMask: false,
  proceduresNeedleThoracicDecompression: false,

  proceduresChestDrain: false,
  proceduresChestDrainValue: "",

  proceduresMiniCricothyrotomy: false,
  proceduresTracheostomy: false,
  proceduresNonInvasiveVentilation: false,
  proceduresMechanicalVentilation: false,

  proceduresPeripheralVenousAccess: false,
  proceduresPeripheralVenousAccessCount: "",

  proceduresIntraosseousAccess: false,
  proceduresIntraosseousAccessCount: "",

  proceduresCentralVenousAccess: false,
  proceduresCentralVenousAccessValue: "",

  proceduresPvcMeasurement: false,
  proceduresThrombolysisAmi: false,
  proceduresThrombolysisStroke: false,
  proceduresThrombolysisPep: false,

  proceduresArterialAccess: false,
  proceduresIntramuscularInjection: false,
  proceduresSubcutaneousInjection: false,
  proceduresIntradermalInjection: false,
  proceduresIntranasalAdministration: false,
  proceduresNebulization: false,
  proceduresExternalChestCompressions: false,
  proceduresInvasiveBpMeasurement: false,
  proceduresEkgMonitoring: false,
  proceduresO2SatMonitoring: false,
  proceduresCapnometry: false,

  proceduresOtherMonitoring: "",
  proceduresManualDefibrillation: false,
  proceduresAutomaticDefibrillation: false,
  proceduresCardioversion: false,

  proceduresTranscutaneousPm: false,
  proceduresTranscutaneousPmValue: "",

  proceduresTransvenousPm: false,
  proceduresTransvenousPmValue: "",

  proceduresAnalgosedation: false,
  proceduresLocalAnesthesia: false,
  proceduresShortIvAnesthesia: false,

  proceduresPericardialPuncture: false,
  proceduresPeritonealDiagnosticLavage: false,
  proceduresActiveRewarming: false,
  proceduresPassiveRewarming: false,

  proceduresGastricLavage: false,
  proceduresGastricLavageValue: "",

  proceduresNasogastricTube: false,
  proceduresNasogastricTubeValue: "",

  proceduresUrinaryCatheter: false,
  proceduresUrinaryCatheterValue: "",

  proceduresCervicalCollar: false,
  proceduresScoopStretcher: false,
  proceduresSpineBoard: false,
  proceduresLimbImmobilization: false,

  proceduresSplint: false,
  proceduresSplintValue: "",

  proceduresCastDevice: false,
  proceduresWoundCleaning: false,
  proceduresSuture: false,
  proceduresMessage: false,
  proceduresNasalPacking: false,

  proceduresShortSedation: false,
  proceduresProceduralSedation: false,
  proceduresLongSedation: false,
  proceduresArterialPuncture: false,

  proceduresOther: "",
  proceduresObservations: "",

  allergies: "",

  doctorName: "",
  doctorSignature: "",
  doctorSignedAt: null,
  nurseName: "",
  nurseSignature: "",
  nurseSignedAt: null,
};

export const initialDischargeState = {
  hospitalName: "",
  sectionName: "",
  foNumber: "",
  firstName: "",
  lastName: "",
  birthDate: "",
  age: "",
  diagnosisAtAdmission: "",
  appliedProcedures: "",
  diagnosisAtDischarge: "",
  patientStateAtDischarge: "",
  dischargeHour: "",
  admittedSection: "",
  transferredSection: "",
  leavesWithRecommendations: false,
  treatmentAndRecommendations: "",

  doctorName: "",
  doctorSignature: "",
  doctorSignedAt: null,
  nurseName: "",
  nurseSignature: "",
  nurseSignedAt: null,
};