import { toIntOrNull, toFloatOrNull } from "./formsPageHelpers";

function toIsoDateOrNull(value) {
  if (!value) return null;

  const parts = String(value).split("/");
  if (parts.length !== 3) return value;

  const [day, month, year] = parts;

  if (!day || !month || !year) return null;

  return `${year}-${month.padStart(2, "0")}-${day.padStart(2, "0")}`;
}

export function buildAiTriagePayload(preform) {
  return {
    varsta: Number(preform.age || 40),
    sex: preform.sex === "F" ? 2 : 1,
    temperatura: Number(preform.temperature || 36.8),
    puls: Number(preform.pulse || preform.av || 80),
    respiratie: Number(preform.respiratoryRate || 18),
    ta_sistolica: Number(preform.systolicBp || 120),
    ta_diastolica: Number(preform.diastolicBp || 80),
    saturatie: Number(preform.spo2 || 98),
    durere: Number(preform.painScale || 0),
    ambulanta:
      preform.broughtByCode === "13_SAJ" ||
      preform.broughtByCode === "14_SMURD"
        ? 1
        : 2,

    fara_puls:
      preform.pickupStopCr ||
      preform.pickupDeceased ||
      preform.pickupResuscitationInProgress
        ? 1
        : 0,

    detresa_respiratorie_severa:
      preform.dyspnea && Number(preform.spo2 || 98) < 90 ? 1 : 0,

    sangerare_majora:
      preform.giHematemesis ||
      preform.giMelena ||
      preform.giRectorrhagia ||
      preform.guVaginalBleeding
        ? 1
        : 0,

    INJURY: preform.pickupTrauma ? 1 : 0,
    CAD: preform.historyCardiac ? 1 : 0,
    CHF: preform.historyCardiac ? 1 : 0,
    COPD: preform.historyPulmonary ? 1 : 0,
    ASTHMA: preform.historyPulmonary ? 1 : 0,
    CKD: preform.historyRenal ? 1 : 0,
    ESRD: preform.historyRenal ? 1 : 0,
    DIABTYP2: preform.historyDiabetes ? 1 : 0,

    motiv1: "0",
    motiv2: "0",
    motiv3: "0",
  };
}

export function buildPreformPayload(preform) {
  const { aiTriageResult, painScale, ...cleanPreform } = preform;

  return {
    ...cleanPreform,
    age: toIntOrNull(preform.age),
    birthDate: toIsoDateOrNull(preform.birthDate),
    gcs: toIntOrNull(preform.gcs),
    gcsM: toIntOrNull(preform.gcsM),
    gcsV: toIntOrNull(preform.gcsV),
    gcsO: toIntOrNull(preform.gcsO),
    heightCm: toIntOrNull(preform.heightCm),
    weightKg: toFloatOrNull(preform.weightKg),
    respiratoryRate: toIntOrNull(preform.respiratoryRate),
    pulse: toIntOrNull(preform.pulse),
    systolicBp: toIntOrNull(preform.systolicBp),
    diastolicBp: toIntOrNull(preform.diastolicBp),
    spo2: toIntOrNull(preform.spo2),
    glycemia: toIntOrNull(preform.glycemia),
    temperature: toFloatOrNull(preform.temperature),

    doctorName: preform.doctorName || "",
    doctorSignature: preform.doctorSignature || "",
    doctorSignedAt: preform.doctorSignedAt || null,
    nurseName: preform.nurseName || "",
    nurseSignature: preform.nurseSignature || "",
    nurseSignedAt: preform.nurseSignedAt || null,

    details: JSON.stringify({
      aiTriageResult: aiTriageResult || null,
painScale: toIntOrNull(painScale),
      objectiveGeneralState: preform.objectiveGeneralState || "",

      headNormal: preform.headNormal || false,
      headTraumaMark: preform.headTraumaMark || false,
      headOralLesions: preform.headOralLesions || false,
      headDentalLesions: preform.headDentalLesions || false,

      neckNormal: preform.neckNormal || false,
      neckTraumaMark: preform.neckTraumaMark || false,
      neckPalpableFormations: preform.neckPalpableFormations || false,
      neckOther: preform.neckOther || "",

      noseNostrilsNormal: preform.noseNostrilsNormal || false,
      noseMucosaNormal: preform.noseMucosaNormal || false,
      noseOther: preform.noseOther || "",
      noseEpistaxisLeft: preform.noseEpistaxisLeft || false,
      noseEpistaxisRight: preform.noseEpistaxisRight || false,
      noseForeignBodyLeft: preform.noseForeignBodyLeft || false,
      noseForeignBodyRight: preform.noseForeignBodyRight || false,
      noseTraumaLeft: preform.noseTraumaLeft || false,
      noseTraumaRight: preform.noseTraumaRight || false,

      earTympanicMembraneNormal: preform.earTympanicMembraneNormal || false,
      earExternalCanalsNormal: preform.earExternalCanalsNormal || false,
      earAuricleNormal: preform.earAuricleNormal || false,
      earOther: preform.earOther || "",
      earOtorrhagiaLeft: preform.earOtorrhagiaLeft || false,
      earOtorrhagiaRight: preform.earOtorrhagiaRight || false,
      earForeignBodyLeft: preform.earForeignBodyLeft || false,
      earForeignBodyRight: preform.earForeignBodyRight || false,
      earHemotympanumLeft: preform.earHemotympanumLeft || false,
      earHemotympanumRight: preform.earHemotympanumRight || false,
      earTraumaLeft: preform.earTraumaLeft || false,
      earTraumaRight: preform.earTraumaRight || false,

      eyeMobilityNormal: preform.eyeMobilityNormal || false,
      eyePupilsNormal: preform.eyePupilsNormal || false,
      eyeExamOther: preform.eyeExamOther || "",
      eyeConjunctivitisLeft: preform.eyeConjunctivitisLeft || false,
      eyeConjunctivitisRight: preform.eyeConjunctivitisRight || false,
      eyeMydriasisLeft: preform.eyeMydriasisLeft || false,
      eyeMydriasisRight: preform.eyeMydriasisRight || false,
      eyeMiosisLeft: preform.eyeMiosisLeft || false,
      eyeMiosisRight: preform.eyeMiosisRight || false,
      eyeNystagmusLeft: preform.eyeNystagmusLeft || false,
      eyeNystagmusRight: preform.eyeNystagmusRight || false,
      eyeDeviationLeft: preform.eyeDeviationLeft || false,
      eyeDeviationRight: preform.eyeDeviationRight || false,
      eyeTraumaExamLeft: preform.eyeTraumaExamLeft || false,
      eyeTraumaExamRight: preform.eyeTraumaExamRight || false,

      cvRhythmNormal: preform.cvRhythmNormal || false,
      cvPeripheralPulseNormal: preform.cvPeripheralPulseNormal || false,
      cvHeartAuscultationNormal: preform.cvHeartAuscultationNormal || false,
      cvIrregularPulse: preform.cvIrregularPulse || false,
      cvFiliformPeripheralPulse: preform.cvFiliformPeripheralPulse || false,
      cvPulseDeficit: preform.cvPulseDeficit || false,
      cvArrhythmicSounds: preform.cvArrhythmicSounds || false,
      cvMuffledSounds: preform.cvMuffledSounds || false,
      cvPericardialRub: preform.cvPericardialRub || false,
      cvJugularTurgor: preform.cvJugularTurgor || false,
      cvSystolicMurmur: preform.cvSystolicMurmur || false,
      cvDiastolicMurmur: preform.cvDiastolicMurmur || false,
      cvAorticMurmur: preform.cvAorticMurmur || false,
      cvGallop: preform.cvGallop || false,
      cvCarotidMurmur: preform.cvCarotidMurmur || false,
      cvObservations: preform.cvObservations || "",

      respThoraxAspectNormal: preform.respThoraxAspectNormal || false,
      respThoraxPercussionNormal: preform.respThoraxPercussionNormal || false,
      respVesicularBilateralNormal: preform.respVesicularBilateralNormal || false,
      respOropharynxNormal: preform.respOropharynxNormal || false,
      respDiminishedMurmurLeft: preform.respDiminishedMurmurLeft || false,
      respDiminishedMurmurRight: preform.respDiminishedMurmurRight || false,
      respAbsentMurmurLeft: preform.respAbsentMurmurLeft || false,
      respAbsentMurmurRight: preform.respAbsentMurmurRight || false,
      respWheezingRalesLeft: preform.respWheezingRalesLeft || false,
      respWheezingRalesRight: preform.respWheezingRalesRight || false,
      respCrepitantRalesLeft: preform.respCrepitantRalesLeft || false,
      respCrepitantRalesRight: preform.respCrepitantRalesRight || false,
      respSubcrepitantRalesLeft: preform.respSubcrepitantRalesLeft || false,
      respSubcrepitantRalesRight: preform.respSubcrepitantRalesRight || false,
      respIntercostalRetractionLeft: preform.respIntercostalRetractionLeft || false,
      respIntercostalRetractionRight: preform.respIntercostalRetractionRight || false,
      respSubcutaneousEmphysemaLeft: preform.respSubcutaneousEmphysemaLeft || false,
      respSubcutaneousEmphysemaRight: preform.respSubcutaneousEmphysemaRight || false,
      respTracheaDeviationLeft: preform.respTracheaDeviationLeft || false,
      respTracheaDeviationRight: preform.respTracheaDeviationRight || false,
      respWheezing: preform.respWheezing || false,
      respOther: preform.respOther || "",

      abdomenNormal: preform.abdomenNormal || false,
      abdomenPalpation: preform.abdomenPalpation || false,
      abdomenPercussion: preform.abdomenPercussion || false,
      abdomenBowelTransit: preform.abdomenBowelTransit || false,
      abdomenRectalExam: preform.abdomenRectalExam || false,
      abdomenDistended: preform.abdomenDistended || false,
      abdomenTransitAbsent: preform.abdomenTransitAbsent || false,
      abdomenHepatomegaly: preform.abdomenHepatomegaly || false,
      abdomenSplenomegaly: preform.abdomenSplenomegaly || false,
      abdomenPalpableMass: preform.abdomenPalpableMass || false,
      abdomenTenderness: preform.abdomenTenderness || false,
      abdomenRectalPositive: preform.abdomenRectalPositive || false,
      abdomenPeritonealIrritation: preform.abdomenPeritonealIrritation || false,
      abdomenObservations: preform.abdomenObservations || "",

      skinExamNormal: preform.skinExamNormal || false,
      skinExamWarm: preform.skinExamWarm || false,
      skinExamCold: preform.skinExamCold || false,
      skinExamWet: preform.skinExamWet || false,
      skinExamDry: preform.skinExamDry || false,
      skinExamPruritus: preform.skinExamPruritus || false,
      skinExamExcoriations: preform.skinExamExcoriations || false,
      skinExamEcchymosis: preform.skinExamEcchymosis || false,
      skinExamPetechiae: preform.skinExamPetechiae || false,
      skinExamPurpura: preform.skinExamPurpura || false,
      skinExamJaundice: preform.skinExamJaundice || false,
      skinExamWounds: preform.skinExamWounds || false,
      skinExamPale: preform.skinExamPale || false,
      skinExamCyanosis: preform.skinExamCyanosis || false,
      skinExamSweaty: preform.skinExamSweaty || false,
      skinExamOther: preform.skinExamOther || "",
      skinExamLocation: preform.skinExamLocation || "",

      guExamNormal: preform.guExamNormal || false,
      guExternalGenitals: preform.guExternalGenitals || false,
      guRegularMenstruation: preform.guRegularMenstruation || false,
      guRectalExam: preform.guRectalExam || false,
      guLastMenstruationDate: preform.guLastMenstruationDate || "",
      guBloodyVaginalDischarge: preform.guBloodyVaginalDischarge || false,
      guLeucorrhea: preform.guLeucorrhea || false,
      guCervixSensitivity: preform.guCervixSensitivity || false,
      guEnlargedUterus: preform.guEnlargedUterus || false,
      guLateroUterineMass: preform.guLateroUterineMass || false,
      guGiordanoLeft: preform.guGiordanoLeft || false,
      guGiordanoRight: preform.guGiordanoRight || false,
      guTesticularSwellingLeft: preform.guTesticularSwellingLeft || false,
      guTesticularSwellingRight: preform.guTesticularSwellingRight || false,
      guTesticularPainLeft: preform.guTesticularPainLeft || false,
      guTesticularPainRight: preform.guTesticularPainRight || false,
      guBreastMassLeft: preform.guBreastMassLeft || false,
      guBreastMassRight: preform.guBreastMassRight || false,
      guTraumaLeft: preform.guTraumaLeft || false,
      guTraumaRight: preform.guTraumaRight || false,
      guExamHematuria: preform.guExamHematuria || false,
      guExamOther: preform.guExamOther || "",

      locomotorExamNormal: preform.locomotorExamNormal || false,
      locomotorHead: preform.locomotorHead || false,
      locomotorNeck: preform.locomotorNeck || false,
      locomotorTrunk: preform.locomotorTrunk || false,
      locomotorUpperLimbs: preform.locomotorUpperLimbs || false,
      locomotorLowerLimbs: preform.locomotorLowerLimbs || false,
      locomotorPulseCarotidLeft: preform.locomotorPulseCarotidLeft || false,
      locomotorPulseCarotidRight: preform.locomotorPulseCarotidRight || false,
      locomotorPulseBrachialLeft: preform.locomotorPulseBrachialLeft || false,
      locomotorPulseBrachialRight: preform.locomotorPulseBrachialRight || false,
      locomotorPulseRadialLeft: preform.locomotorPulseRadialLeft || false,
      locomotorPulseRadialRight: preform.locomotorPulseRadialRight || false,
      locomotorPulseFemoralLeft: preform.locomotorPulseFemoralLeft || false,
      locomotorPulseFemoralRight: preform.locomotorPulseFemoralRight || false,
      locomotorPulsePoplitealLeft: preform.locomotorPulsePoplitealLeft || false,
      locomotorPulsePoplitealRight: preform.locomotorPulsePoplitealRight || false,
      locomotorPulsePedialLeft: preform.locomotorPulsePedialLeft || false,
      locomotorPulsePedialRight: preform.locomotorPulsePedialRight || false,
      locomotorExamPain: preform.locomotorExamPain || false,
      locomotorExamSwelling: preform.locomotorExamSwelling || false,
      locomotorExamEdema: preform.locomotorExamEdema || false,
      locomotorExamFunctionalImpairment: preform.locomotorExamFunctionalImpairment || false,
      locomotorExamCyanosis: preform.locomotorExamCyanosis || false,
      locomotorExamOpenFracture: preform.locomotorExamOpenFracture || false,
      locomotorExamClosedFracture: preform.locomotorExamClosedFracture || false,
      locomotorExamObservations: preform.locomotorExamObservations || "",

      neuroPsychNormal: preform.neuroPsychNormal || false,
      neuroPsychOriented: preform.neuroPsychOriented || false,
      neuroPsychCranialNerves: preform.neuroPsychCranialNerves || false,
      neuroPsychMotor: preform.neuroPsychMotor || false,
      neuroPsychSensitive: preform.neuroPsychSensitive || false,
      neuroPsychRot: preform.neuroPsychRot || false,
      neuroPsychHallucinations: preform.neuroPsychHallucinations || false,
      neuroPsychDelirium: preform.neuroPsychDelirium || false,
      neuroPsychBehaviorDisorders: preform.neuroPsychBehaviorDisorders || false,
      neuroPsychAgitated: preform.neuroPsychAgitated || false,
      neuroPsychObnubilated: preform.neuroPsychObnubilated || false,
      neuroPsychConfused: preform.neuroPsychConfused || false,
      neuroPsychPhotophobia: preform.neuroPsychPhotophobia || false,
      neuroPsychNeckStiffness: preform.neuroPsychNeckStiffness || false,
      neuroPsychParesthesia: preform.neuroPsychParesthesia || false,
      neuroPsychAtaxia: preform.neuroPsychAtaxia || false,
      neuroPsychAphasia: preform.neuroPsychAphasia || false,
      neuroPsychMyoclonus: preform.neuroPsychMyoclonus || false,
      neuroPsychConvulsions: preform.neuroPsychConvulsions || false,
      neuroPsychPlegiaLeft: preform.neuroPsychPlegiaLeft || false,
      neuroPsychPlegiaRight: preform.neuroPsychPlegiaRight || false,
      neuroPsychParesisLeft: preform.neuroPsychParesisLeft || false,
      neuroPsychParesisRight: preform.neuroPsychParesisRight || false,
      neuroPsychAnesthesiaLeft: preform.neuroPsychAnesthesiaLeft || false,
      neuroPsychAnesthesiaRight: preform.neuroPsychAnesthesiaRight || false,
      neuroPsychBabinskiLeft: preform.neuroPsychBabinskiLeft || false,
      neuroPsychBabinskiRight: preform.neuroPsychBabinskiRight || false,
      neuroPsychOther: preform.neuroPsychOther || "",
      neuroPsychObservations: preform.neuroPsychObservations || "",

      proceduresO2Mask: preform.proceduresO2Mask || false,
      proceduresO2MaskValue: preform.proceduresO2MaskValue || "",
      proceduresGuedelCannula: preform.proceduresGuedelCannula || false,
      proceduresOralCavityAspiration: preform.proceduresOralCavityAspiration || false,
      proceduresIotTubeAspiration: preform.proceduresIotTubeAspiration || false,
      proceduresIotTubeAspirationValue: preform.proceduresIotTubeAspirationValue || "",
      proceduresIotWithInduction: preform.proceduresIotWithInduction || false,
      proceduresIotWithoutInduction: preform.proceduresIotWithoutInduction || false,
      proceduresIntWithInduction: preform.proceduresIntWithInduction || false,
      proceduresCombitube: preform.proceduresCombitube || false,
      proceduresLaryngealMask: preform.proceduresLaryngealMask || false,
      proceduresNeedleThoracicDecompression: preform.proceduresNeedleThoracicDecompression || false,
      proceduresChestDrain: preform.proceduresChestDrain || false,
      proceduresChestDrainValue: preform.proceduresChestDrainValue || "",
      proceduresMiniCricothyrotomy: preform.proceduresMiniCricothyrotomy || false,
      proceduresTracheostomy: preform.proceduresTracheostomy || false,
      proceduresNonInvasiveVentilation: preform.proceduresNonInvasiveVentilation || false,
      proceduresMechanicalVentilation: preform.proceduresMechanicalVentilation || false,
      proceduresPeripheralVenousAccess: preform.proceduresPeripheralVenousAccess || false,
      proceduresPeripheralVenousAccessCount: preform.proceduresPeripheralVenousAccessCount || "",
      proceduresIntraosseousAccess: preform.proceduresIntraosseousAccess || false,
      proceduresIntraosseousAccessCount: preform.proceduresIntraosseousAccessCount || "",
      proceduresCentralVenousAccess: preform.proceduresCentralVenousAccess || false,
      proceduresCentralVenousAccessValue: preform.proceduresCentralVenousAccessValue || "",
      proceduresPvcMeasurement: preform.proceduresPvcMeasurement || false,
      proceduresThrombolysisAmi: preform.proceduresThrombolysisAmi || false,
      proceduresThrombolysisStroke: preform.proceduresThrombolysisStroke || false,
      proceduresThrombolysisPep: preform.proceduresThrombolysisPep || false,
      proceduresArterialAccess: preform.proceduresArterialAccess || false,
      proceduresIntramuscularInjection: preform.proceduresIntramuscularInjection || false,
      proceduresSubcutaneousInjection: preform.proceduresSubcutaneousInjection || false,
      proceduresIntradermalInjection: preform.proceduresIntradermalInjection || false,
      proceduresIntranasalAdministration: preform.proceduresIntranasalAdministration || false,
      proceduresNebulization: preform.proceduresNebulization || false,
      proceduresExternalChestCompressions: preform.proceduresExternalChestCompressions || false,
      proceduresInvasiveBpMeasurement: preform.proceduresInvasiveBpMeasurement || false,
      proceduresEkgMonitoring: preform.proceduresEkgMonitoring || false,
      proceduresO2SatMonitoring: preform.proceduresO2SatMonitoring || false,
      proceduresCapnometry: preform.proceduresCapnometry || false,
      proceduresOtherMonitoring: preform.proceduresOtherMonitoring || "",
      proceduresManualDefibrillation: preform.proceduresManualDefibrillation || false,
      proceduresAutomaticDefibrillation: preform.proceduresAutomaticDefibrillation || false,
      proceduresCardioversion: preform.proceduresCardioversion || false,
      proceduresTranscutaneousPm: preform.proceduresTranscutaneousPm || false,
      proceduresTranscutaneousPmValue: preform.proceduresTranscutaneousPmValue || "",
      proceduresTransvenousPm: preform.proceduresTransvenousPm || false,
      proceduresTransvenousPmValue: preform.proceduresTransvenousPmValue || "",
      proceduresAnalgosedation: preform.proceduresAnalgosedation || false,
      proceduresLocalAnesthesia: preform.proceduresLocalAnesthesia || false,
      proceduresShortIvAnesthesia: preform.proceduresShortIvAnesthesia || false,
      proceduresPericardialPuncture: preform.proceduresPericardialPuncture || false,
      proceduresPeritonealDiagnosticLavage: preform.proceduresPeritonealDiagnosticLavage || false,
      proceduresActiveRewarming: preform.proceduresActiveRewarming || false,
      proceduresPassiveRewarming: preform.proceduresPassiveRewarming || false,
      proceduresGastricLavage: preform.proceduresGastricLavage || false,
      proceduresGastricLavageValue: preform.proceduresGastricLavageValue || "",
      proceduresNasogastricTube: preform.proceduresNasogastricTube || false,
      proceduresNasogastricTubeValue: preform.proceduresNasogastricTubeValue || "",
      proceduresUrinaryCatheter: preform.proceduresUrinaryCatheter || false,
      proceduresUrinaryCatheterValue: preform.proceduresUrinaryCatheterValue || "",
      proceduresCervicalCollar: preform.proceduresCervicalCollar || false,
      proceduresScoopStretcher: preform.proceduresScoopStretcher || false,
      proceduresSpineBoard: preform.proceduresSpineBoard || false,
      proceduresLimbImmobilization: preform.proceduresLimbImmobilization || false,
      proceduresSplint: preform.proceduresSplint || false,
      proceduresSplintValue: preform.proceduresSplintValue || "",
      proceduresCastDevice: preform.proceduresCastDevice || false,
      proceduresWoundCleaning: preform.proceduresWoundCleaning || false,
      proceduresSuture: preform.proceduresSuture || false,
      proceduresMessage: preform.proceduresMessage || false,
      proceduresNasalPacking: preform.proceduresNasalPacking || false,
      proceduresShortSedation: preform.proceduresShortSedation || false,
      proceduresProceduralSedation: preform.proceduresProceduralSedation || false,
      proceduresLongSedation: preform.proceduresLongSedation || false,
      proceduresArterialPuncture: preform.proceduresArterialPuncture || false,
      proceduresOther: preform.proceduresOther || "",
      proceduresObservations: preform.proceduresObservations || "",
    }),
  };
}

export function buildDischargePayload(discharge) {
  const hospitalizationOutcomeMap = {
    AMELIORAT: "AMELIORAT",
    STATIONAR: "STATIONAR",
    AGRAVAT: "AGRAVAT",
    DECEDAT: "DECEDAT",
  };

  let dischargeType = "EXTERNAT";
  if (discharge.transferredSection?.trim()) {
    dischargeType = "TRANSFERAT";
  } else if (discharge.admittedSection?.trim()) {
    dischargeType = "INTERNAT";
  }

  return {
    ...discharge,
    doctorName: discharge.doctorName || "",
    doctorSignature: discharge.doctorSignature || "",
    doctorSignedAt: discharge.doctorSignedAt || null,
    nurseName: discharge.nurseName || "",
    nurseSignature: discharge.nurseSignature || "",
    nurseSignedAt: discharge.nurseSignedAt || null,
    details: JSON.stringify({
      appliedProcedures: discharge.appliedProcedures || "",
      patientStateAtDischarge: discharge.patientStateAtDischarge || "",
      dischargeHour: discharge.dischargeHour || "",
      admittedSection: discharge.admittedSection || "",
      transferredSection: discharge.transferredSection || "",
      leavesWithRecommendations: discharge.leavesWithRecommendations || false,
    }),
    citizenshipType: "ROMANA",
    insuranceStatus: "ASIGURAT_CNAS",
    admissionType: "URGENTA",
    hospitalizationOutcome:
      hospitalizationOutcomeMap[discharge.patientStateAtDischarge] || "AMELIORAT",
    dischargeType,
  };
}